
services:
  preprocessing:
    image: preprocessing:latest
    container_name: preprocessing
    volumes:
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/datasets:/datasets
    command: tail -f /dev/null

  training:
    image: training:latest
    container_name: training
    volumes:
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/datasets:/datasets
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/model_registry:/model_registry
    command: tail -f /dev/null

  training-pipeline:
    image: training_pipeline:latest
    container_name: training_pipeline
    volumes:
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/datasets:/datasets
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/model_registry:/model_registry
    command: tail -f /dev/null

