services:
  training-pipeline:
    image: training_pipeline:latest
    container_name: training-pipeline
    volumes:
      - ./datasets:/datasets
      - ./model_registry:/model_registry
      - ./metrics:/metrics
      - ./config.json:/app/config.json

  model-serving:
    image: model-serving:latest
    container_name: model-serving
    volumes:
      - ./model_registry:/model_registry
      - ./config.json:/app/config.json
    ports: 
      - 8000:8000