services:
  training-pipeline:
    image: model-serving:latest
    container_name: model-serving
    volumes:
      - C:/Users/jpabl/OneDrive/Documentos/xtream-ai-assignment-engineer/model_registry:/model_registry
    command: tail -f /dev/null
    ports: 
      - 8000:8000